# Generated by Django 2.2.10 on 2021-11-16 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, unique=True)),
                ('vote', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['-question'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('start_at', models.DateField(auto_now_add=True)),
                ('finish_at', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_at'],
                'unique_together': {('start_at', 'finish_at')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('sin', 'Single_choice'), ('mul', 'Multi_choice'), ('tex', 'Text')], default='tex', max_length=3)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='opros.Survey')),
            ],
            options={
                'ordering': ['-survey'],
            },
        ),
        migrations.CreateModel(
            name='PartiSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('answer_text', models.CharField(max_length=100, null=True, verbose_name='text_answer')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_choosed', to='opros.Option')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to='opros.Question')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='opros.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='opros.Question'),
        ),
    ]
