# Generated by Django 2.2.10 on 2021-11-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='vote',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
