# Generated by Django 2.2.10 on 2021-10-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partisession',
            name='user',
        ),
    ]
